# Site settings
title: moad
email: music@moad.info
description: 3 guys, plenty of instruments and a few PCs, moving between experimental indie and electronic rock
baseurl: "" # /moad-site
url: "moad.info" # the base hostname & protocol for your site
twitter_username:
facebook_username: moad.band
youtube_username: moad videos
soundcloud_username:
itunes_username: itunes
spotify_username: moad
instagram_username:


# Build settings
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Collections
